### ISSUE TITLE
how does this work?

### ISSUE THREAD

**Issue by vvo** [damianprzygodzki/react-atomic-wrapper#1]
Hi! I am very curious, could you put a demo or a more complete readme to understand what you are solving? Thanks!

**Comment by damianprzygodzki** [comment]
@vvo Of course, the project is only 1 day long, i didn't had time yesterday to provide full demo but i am gonna provide it asap :)

**Comment by damianprzygodzki** [comment]
https://github.com/damianprzygodzki/react-atomic-wrapper/blob/master/README.md
